# Pre-commit hooks for zsh-llm-suggestions
# Install: uv pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-all
        # Only check src/ directory to avoid test files
        files: ^src/

  # pytest - Run unit tests before commit
  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest (unit tests only)
        entry: bash -c 'SKIP_INTEGRATION_TESTS=1 ZSH_LLM_DISABLE_PYGMENTS=1 uv run pytest -q tests/'
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

  # Standard pre-commit hooks for file quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]
