blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability (Private)
    url: https://github.com/cearley/zsh-llm-suggestions/blob/master/SECURITY_AUDIT.md
    about: Report security vulnerabilities privately via email (see SECURITY_AUDIT.md for contact)
  - name: Documentation
    url: https://github.com/cearley/zsh-llm-suggestions#readme
    about: Read the README and documentation
  - name: Contributing Guide
    url: https://github.com/cearley/zsh-llm-suggestions/blob/master/CONTRIBUTING.md
    about: Learn how to contribute to the project
